Don't allow malformed turn urls when passing array of objects.
When the ua config contained a malformed url:

    turnServers: [
      {
        urls: ['turn:stun.example.com:3478', 'turn:stun.example.com?transport=tcp', 'turns:stun.example.com:443?transport=tcp'],
        username: 'alice',
        password: 'pass'
      },
      {
        urls: [''],
        username: 'alice',
        password: 'pass'
      }
    ]

the turnServer function only checked/tested the first objects urls.
(Second for loop `idx` would increment to 3. So the second `turn_server` would
be skipped.) The malformed urls would be passed on to:

    new SIP.WebRTC.RTCPeerConnection({'iceServers': servers}, this.RTCConstraints);

and result in:

    Uncaught TypeError: Failed to construct 'RTCPeerConnection': Malformed URL (Chrome)
    Error: RTCPeerConnection constructor passed invalid RTCConfiguration - missing url (Firefox)