src/SIP.js - declare SIP variable per-environment
This allows multiple requires with given environments:

    require('sip.js/src/SIP')(require('sip.js/src/environment'));
    require('sip.js/src/SIP')(require('sip.js/src/environment'));

without encountering an error like:

    /private/tmp/requiretwice/node_modules/sip.js/src/SIP.js:12
    Object.defineProperties(SIP, {
           ^
    TypeError: Cannot redefine property: version
        at Function.defineProperties (native)
        at module.exports (/private/tmp/requiretwice/node_modules/sip.js/src/SIP.js:12:8)
        at Object.<anonymous> (/private/tmp/requiretwice/index.js:3:26)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:906:3

or having the different instances interfere with each other.